### ISSUE TITLE
how yo get the package "FyTok-0.0.0-py3-none-any.whl "?

### ISSUE THREAD

**Issue by fengdut** [fusion-yun/fytok_tutorial#10]
In FyTok_Installation.ipynb
to install the fytok, the 'FyTok-0.0.0-py3-none-any.whl ' is needed. 
Where can I get it?

**Comment by simpla-fusion** [comment]
最新版 fytok，可以通过 pip install fytok 安装
历史版本参见 https://pypi.org/project/fytok/#history
