### ISSUE TITLE
ch2_data_and_view 运行报错

### ISSUE THREAD

**Issue by cameron572366** [fusion-yun/fytok_tutorial#3]
我是对ch2_data_and_view这个jupyter脚本中各个代码块逐个运行的。当运行到 wall = Wall("east://#wall") 这行时，报了错误。请问我是哪里安装有问题的吗？
![image](https://github.com/fusion-yun/fytok_tutorial/assets/56440690/da0cb3f7-e8aa-4193-aca4-fa415e741c77)

但是运行import fytok 这行时，是能正常输出fytok图案的，如下图。
![image](https://github.com/fusion-yun/fytok_tutorial/assets/56440690/59bd7adc-370d-4ab9-90e3-4edfba917832)

**Comment by simpla-fusion** [comment]
lxml 版本问题，退回到4.9.2。下个版本里会升级对 lxml 5 的支持
