### ISSUE TITLE
RuntimeError: Unable to determine mesh type! 

### ISSUE THREAD

**Issue by cameron572366** [fusion-yun/fytok_tutorial#4]
在执行 ch2_data_and_view.ipynb 中的 “type(psi.domain)”时报了这个错
![592e49c2310ede831bb22745141c201](https://github.com/fusion-yun/fytok_tutorial/assets/56440690/b9dc2a99-c5ae-4a52-94e8-8cd735e3ff07)

**Comment by simpla-fusion** [comment]
fixed in 0.5.2
