### ISSUE TITLE
ModuleNotFoundError: No module named 'fytok.contexts'

### ISSUE THREAD

**Issue by cameron572366** [fusion-yun/fytok_tutorial#5]
在运行 ch2_data_and_view.ipynb 这个脚本中的"from fytok.contexts.tokamak import Tokamak"这行时，报了“No module named 'fytok.contexts'”。如下图
![image](https://github.com/fusion-yun/fytok_tutorial/assets/56440690/cedd30d2-0e47-48aa-b96a-2649eab58b0a)

**Comment by simpla-fusion** [comment]
update to 0.5.2
