### ISSUE TITLE
磁探针信号随时间变化的图形中没有数据显示

### ISSUE THREAD

**Issue by cameron572366** [fusion-yun/fytok_tutorial#6]
如图， 在运行 FyTok_module_Device.ipynb 这个脚本时，
![image](https://github.com/fusion-yun/fytok_tutorial/assets/56440690/c1385d2b-814b-4535-a210-8f666df58840)

**Comment by emilylxj** [comment]
磁探针数据是实验测试数据，需要有访问EAST的MDSplus数据库的权限。FyTok无权开放所外访问EAST数据库的权限，因此无法显示数据。后期的算例中会加入某一炮的本地MDS数据，以便测试。
